version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sequelize
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
